feature: Add FairProjectConfig
FairRootGroup/FairCMakeModules pull request #23
Opened 2021-07-22 18:00 UTC by ChristianTackeGSI

Currently it has only one function: fair_get_git_version()

2021-07-22 18:53 UTC, ChristianTackeGSI commented
Should we add a `--always` to the`git describe`?

2021-07-23 11:54 UTC, dennisklein reviewed
https://github.com/FairRootGroup/FairCMakeModules/runs/3138860144?check_suite_focus=true#step:5:26 Is this behavior intended?

2021-07-23 11:57 UTC, dennisklein commented
> Should we add a `--always` to the`git describe`?

To be honest, I do not really understand what it does.

2021-07-23 16:19 UTC, ChristianTackeGSI commented
> https://github.com/FairRootGroup/FairCMakeModules/runs/3138860144?check_suite_focus=true#step:5:26 Is this behavior intended?

I guess, the problem is, that the github CI does not present a full git repository to the build process.

So we could either say: 
→ Okay, that's the case, where we want "don't touch variables" behaviour.

If that's the idea, we might consider to add `ERROR_VARIABLE` to `execute_process()` to hide the error messages. (I am unsure, if this is a good idea.)

Or:

> > Should we add a `--always` to the`git describe`?
> 
> To be honest, I do not really understand what it does.

If `git describe` can't find a good tag, it will return a shortened commit sha1 with that flag.

I have added a commit to show the effect:

```console
-- FairCMakeModules Version 0.2.0 (6c08dde)
```

For the github CI, we get some strange commit sha1. (I guess, it's some merge commit or something like that).

I am also unsure, whether this is really helpful. Maybe it's just "better than nothing"?

2021-07-27 16:51 UTC, dennisklein commented
> I am also unsure, whether this is really helpful. Maybe it's just "better than nothing"?

What would the code look like, if a project wanted to implement the behaviour "Get the git version, but fall back to something else, if a git version is not available"? I believe we should make sure that such a code snippet is not going to get overly complicated / un-readable because of the interface we choose for `fair_get_git_version()`.

2021-07-27 16:56 UTC, dennisklein commented
> > I am also unsure, whether this is really helpful. Maybe it's just "better than nothing"?
> 
> What would the code look like, if a project wanted to implement the behaviour "Get the git version, but fall back to something else, if a git version is not available"? I believe we should make sure that such a code snippet is not going to get overly complicated / un-readable because of the interface we choose for `fair_get_git_version()`.

```cmake
fair_get_git_version()
if(NOT PROJECT_GIT_VERSION)
  # get it from somewhere else
endif()
```

If there is no such logic in the project itself, and a package manage cannot present a git repo, it should also be straightforward to *inject* the version by modifying the source tree, e.g. with a package-level patch:

```diff
- fair_get_git_version()
+ set(PROJECT_GIT_VERSION "v42")
```

Looks simple enough, so from my side I would approve this.

> Maybe it's just "better than nothing"?

I would conclude, yes.

2021-07-27 17:00 UTC, ChristianTackeGSI commented
If we don't implement `--always`:
```cmake
set(PROJECT_GIT_VERSION "your fallback default here")
fair_get_git_version()

# Or
fair_get_git_version(OUTVAR_PREFIX yourprefix)
if(NOT DEFINED yourprefix_GIT_VERSIONyourprefix_GIT_VERSION)
   set(yourprefix_GIT_VERSION "your fallback")
   # Do something else
endif()
```

For the `--always` case the above code would only work for a non-existant / broekn `.git`. Otherwise it would always use the sha1.

In that case, one would do something like
```cmake
fair_get_git_version()
if(NOT DEFINED PROJECT_GIT_VERSION OR PROJECT_GIT_VERSION regex-match-operator "^[0-9a-z][0-9a-z][0-9a-z][0-9a-z]*$")
  # ...
endif()
```

Which obviously is ugly.

2021-07-27 17:02 UTC, dennisklein commented
> If that's the idea, we might consider to add ERROR_VARIABLE to execute_process() to hide the error messages. (I am unsure, if this is a good idea.)

Actually, what about having an option `FATAL_ERROR` (or `REQUIRED`) which is by default `OFF` - meaning it would silence the error message and otherwise turn the output of git describe into a fatal cmake error (possibly with some additional comments).

2021-08-05 14:15 UTC, dennisklein requested changes

2021-08-05 14:15 UTC, dennisklein commented on src/modules/FairProjectConfig.cmake
> +  if(GIT_FOUND AND EXISTS ${CMAKE_SOURCE_DIR}/.git)
```suggestion
  if(Git_FOUND AND EXISTS ${CMAKE_SOURCE_DIR}/.git)
```

The find module also sets `GIT_FOUND` but `Git_FOUND` is the more modern convention.

2021-08-05 14:15 UTC, dennisklein commented on src/modules/FairProjectConfig.cmake
> +    execute_process(COMMAND ${GIT_EXECUTABLE} describe --tags --dirty ${git_always} --match "v*"
```suggestion
    # TODO use this form once this module requires CMake 3.14
    # execute_process(COMMAND $<TARGET_FILE:Git::Git> describe --tags --dirty ${git_always} --match "v*"
    execute_process(COMMAND ${GIT_EXECUTABLE} describe --tags --dirty ${git_always} --match "v*"
```

2021-08-05 14:15 UTC, dennisklein commented on src/modules/FairProjectConfig.cmake
> +  if(GIT_FOUND AND EXISTS ${CMAKE_SOURCE_DIR}/.git)
the existance check for `.git` is fragile, consider using `git rev-parse --is-inside-work-tree` or similar (not sure how recent the `--is-inside-work-tree` flag is, also see e.g. https://remarkablemark.org/blog/2020/06/05/check-git-repository/)

2021-08-05 15:02 UTC, ChristianTackeGSI commented on src/modules/FairProjectConfig.cmake
> +  if(GIT_FOUND AND EXISTS ${CMAKE_SOURCE_DIR}/.git)
What about dropping the existence check completely and letting `git describe` handle it?

```console
CMake Error at src/modules/FairProjectConfig.cmake:91 (message):
  git describe failed (return value 128):

  fatal: not a git repository (or any parent up to mount point /)

  Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

2021-08-05 15:18 UTC, dennisklein approved these changes

2021-08-05 16:44 UTC, merged