Import `fair_generate_package_dependencies`
FairRootGroup/FairCMakeModules pull request #8
Opened 2021-05-09 13:53 UTC by ChristianTackeGSI

* Import `generate_package_dependencies` from FairMQ
* Improve and prefix fix `fair_`
* Add simple testsuite

2021-05-10 07:02 UTC, dennisklein requested changes

2021-05-10 07:02 UTC, dennisklein commented on tests/FairFindPackage2/find_package2_simple.cmake
> +endif()
Let's make this more granular on ctest level: E.g. put this into a separate *test* `simple` within a *testsuite* `fair_generate_package_dependencies` (or whatever naming you like ;) )

2021-05-10 08:16 UTC, ChristianTackeGSI commented on tests/FairFindPackage2/find_package2_simple.cmake
> +endif()
Should be addressed.

2021-05-12 07:09 UTC, dennisklein approved these changes

2021-05-12 07:09 UTC, merged